### ISSUE TITLE
Statistically invalid?

### ISSUE THREAD

**Issue by timdp** [dcousens/fisher-yates#1]
I like to view shuffling as repeatedly pulling things from a bag until the bag is empty, and placing them in the order in which they were pulled. Because your code can move the same array element multiple times, it doesn't correspond to this model and therefore doesn't seem mathematically sound to me.

There's an npm module called [knuth-shuffle](https://github.com/coolaj86/knuth-shuffle) that implements the same algorithm, but does so in the way that I'm describing. It also links to a nice [visual representation](http://bost.ocks.org/mike/shuffle/).

(I got here haphazardly by clicking on your username. I decided to take a look at the code because I used to implement shuffling wrong until someone corrected me. It could be that I'm making a wrong assumption in the above, but I wanted to make sure that your module works as expected.)

**Comment by dcousens** [comment]
Hi @timdp!

I didn't expect in-depth feedback on this module for a while yet,  however I welcome it!
The core export of this library is the [Fisher-Yates inside-out](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_.22inside-out.22_algorithm) algorithm for randomly shuffling **and copying** a list/array.

The algorithm employed by `knuth-shuffle` is the standard **in-place** Fisher-Yates algorithm, as can be found in this module also (see [`mutable.js`](https://github.com/dcousens/fisher-yates/blob/master/mutable.js)).
`knuth-shuffle` is a fine library,  however I wanted to play with the inside-out algorithm and provide RNG injection,  so I decided to publish this.

I haven't yet put this implementation through rigorous testing,  but it has passed basic statistical tests for uniformity thus far.

Benchmarks seem to indicate the inside-out algorithm is ~10% faster if you are definitely going to be copying the array.   IMHO immutability in API's is nicer too.

**Comment by timdp** [comment]
Ahh, it sounds like I was misinformed then. Carry on!
